### ISSUE TITLE
sentence id

### ISSUE THREAD

**Issue by arademaker** [wmaier/treetools#6]
```
% treetools transform input.xml output.text --src-format tigerxml --dest-format terminals
```

The command above is giving me errors such as 

```
6300
skipping sentence 2619: multiple roots: n-adj s
```

But the 2619 is not the sentence id but the sentence position in the XML file. I found that I need to pass the `continuous` argument so the system will use the `id` argument of the node `<s>` but I didn't know how to pass it. In the transformation help, we have `--transformparams`  and `--src-opts`, but none of these seems to work. Can you help?

**Comment by wmaier** [comment]
The continuous numbering can be produced with `--src-opts continuous`. You can use `treetools transform --usage` to see all available options.

I haven't been able to reproduce the numbering problem you are describing. I've constructed a tigerxml example with a sentence that has multiple roots (`tests/issue-6-example.xml`), but I was able to obtain the terminals just fine with 
```
./treetools transform tests/issue-6-example.xml terminals.txt --src-format tigerxml --dest-format terminals
``` 
The output is `skipping sentence 4: multiple roots: S VROOT`, if I add `--src-opts continuous`, the output is `skipping sentence 3: multiple roots: S VROOT`.

Could there be other differences in the format of the file you are passing to my xml example mentioned above?

**Comment by wmaier** [comment]
I will close this issue for now, feel free to reopen if the problem persists.
